### ISSUE TITLE
Return to fullscreen button not appearing; Page frozen after pausing. 

### ISSUE THREAD

**Issue by AzarTuerxuntuoheti** [lookit/ember-lookit-frameplayer#135]
We are having two issues in the video stimuli frame. 
1. On some instances when the participants exit the full screen mid-trial, they are not getting the green button to go back to full screen. In the meantime, the trial is still going with only partial view. Please see the first screenshot down below where the green button appears correctly, and the second where it doesn't. 
2. On some instances, when the participant exits the full screen during the colorful attention grabber, they are not able to return and continue and the page is just frozen, so the participants just have to restart the entire study. 

We have been able to replicate these issues, but not persistently. This is only happening on occasion even within the same computer, same browser, same settings.

**Which frame or frames does it affect?**
custome frame
exp-lookit-geometry-alternation-open

**Example**
not applicable at the moment, but happened several times on different computers, and have also been not replicable within the same computer, browser, and settings. 

**To Reproduce**
1. Go to https://lookit.mit.edu/exp/studies/
2. Create a fake child and participate in the study. 
3. Proceed through the study until you reach the actual testing frame.
4. During the attention grabber and the test trials, try to exit the fullscreen, or pause the study, to see if the "Please return to full screen" button will appear. 
```
          "alt-trials": {
            "kind": "choice",
            "sampler": "random-parameter-set",
            "frameList": [
                {
                    "altOnLeft": "ALT_ON_LEFT_ODD_TRIALS",
                    "audioSources": "video_01"
                },
                {
                    "altOnLeft": "ALT_ON_LEFT_EVEN_TRIALS",
                    "audioSources": "video_02"
                },
                {
                    "altOnLeft": "ALT_ON_LEFT_ODD_TRIALS",
                    "audioSources": "video_03"
                },
                {
                    "altOnLeft": "ALT_ON_LEFT_EVEN_TRIALS",
                    "audioSources": "video_04",
                    "endAudioSources": "all_done"
                }
            ],
            "parameterSets": [
                {
                    "ALT_ON_LEFT_ODD_TRIALS": true,
                    "ALT_ON_LEFT_EVEN_TRIALS": false,
                    "CONTEXT_TRIANGLE_UNEVEN": true
                },
                {
                    "ALT_ON_LEFT_ODD_TRIALS": false,
                    "ALT_ON_LEFT_EVEN_TRIALS": true,
                    "CONTEXT_TRIANGLE_UNEVEN": true
                },
                {
                    "ALT_ON_LEFT_ODD_TRIALS": true,
                    "ALT_ON_LEFT_EVEN_TRIALS": false,
                    "CONTEXT_TRIANGLE_UNEVEN": false
                },
                {
                    "ALT_ON_LEFT_ODD_TRIALS": false,
                    "ALT_ON_LEFT_EVEN_TRIALS": true,
                    "CONTEXT_TRIANGLE_UNEVEN": false
                }
            ],
            "parameterSetWeights": [
                1,
                1,
                1,
                1
            ],
            "commonFrameProperties": {
                "kind": "exp-lookit-geometry-alternation-open",
                "baseDir": "https://s3.amazonaws.com/lookitcontents/geometry/",
                "context": "CONTEXT_TRIANGLE_UNEVEN",
                "fsAudio": "fullscreen",
                "attnLength": 10,
                "audioTypes": [
                    "mp3",
                    "ogg"
                ],
                "pauseAudio": "pause",
                "videoTypes": [
                    "mp4",
                    "webm"
                ],
                "trialLength": 60,
                "musicSources": "happy-stroll",
                "unpauseAudio": "return_after_pause",
                "videoSources": "attentiongrabber",
                "triangleColor": "#056090",
                "calibrationLength": 3000,
                "triangleLineWidth": 14,
                "calibrationAudioSources": "chimes",
                "calibrationVideoSources": "attention"
            }
        },
```
**Expected behavior**
Whenever fullscreen is exited, is a green button that says "return to full screen" should appear.

**Screenshots**
Correct behavior screenshot: 
[https://labdevelopingmind.hosting.nyu.edu/Stimuli/Lookit/Other/Screen%20Shot%202020-04-07%20at%2011.39.37%20AM.png](url)

Problem screenshot:
https://labdevelopingmind.hosting.nyu.edu/Stimuli/Lookit/Other/Screen%20Shot%202020-04-07%20at%2011.38.07%20AM.png

**Environment (please complete):**
 - Lookit environment: production. Both with preview and with participating. 
 - Operating system: we used a Mac when we could see the problem, unsure what participants used. 
 - Browser: we used chrome, unsure what participants used.

**Comment by kimberscott** [comment]
Thanks very much for the detailed info! I should be able to work on this in the next week.
