### ISSUE TITLE
Request for "now recording" signal when you press record on consent video plus ability to play back consent recording to check it

### ISSUE THREAD

**Issue by khamlin201** [lookit/ember-lookit-frameplayer#141]
Note: This is the correct form to use for ideas that relate to the Lookit frameplayer: anything that would show up when participating in a Lookit study, e.g. a new type of frame, different formatting/ functionality/options on an existing frame, a new type of counterbalancing for longitudinal studies.  

If you have an idea for the participant or experimenter interfaces outside of actual studies, please [create a feature request in lookit-api](https://github.com/lookit/lookit-api/issues/new/choose) instead. (If you're not sure where your idea belongs, don't worry, we can move it :) )

**Is your feature request related to a problem? Please describe.**
As a repeat parent participant, I always find the consent recording part really difficult to understand -- once you press the button there is no obvious indication that recording has started (in fact, it still says "click here to start consent recording", so I find myself unsure it's recording and waiting a while to start. Then I start, and just hope for the best, but there is no way to preview my recording to be sure it worked. The 10+ people we've had try out our study have all mentioned that this part is really confusing. 

**Is your feature request related to a particular frame?**
[E.g., exp-lookit-exit-survey, exp-lookit-observation]
exp-lookit-video-consent, ember-lookit-frameplayer

**Describe your idea or solution**
The ideal feature would include (1) something that comes up and says "now recording!" (or similar), perhaps replacing the "click here to start consent recording" bit, as well as (2) something that lets you check your video to be sure it recorded properly and nothing is cut off. For example, in the exp-video-config-quality frame, parents can record themselves holding the baby and play it back to check that the baby is in the video; something like this would be very helpful.

**Describe alternatives you've considered**
Just adding (1) would be a huge help - but both would be ideal. Currently, we have adjusted our recruitment scripts to explain this confusing part of the process to our parents, but this isn't ideal and won't work for general lookit-based recruitment. 

**Additional context**
If your idea might be useful to other researchers too, do you have any questions for them about how they'd prefer it be implemented?

If applicable, a sketch of how your new frame should look or a marked-up screenshot showing how you want something to change is **super** helpful!

**Comment by kimberscott** [comment]
I think this is a great idea - both (1) the "now recording" indicator and (2) a way to review your video before proceeding. 

For (2) I'm picturing something like an additional numbered step like "Click [play] to make sure you can see and hear yourself making the statement. If not, you can repeat steps 2 and 3 above to try again!" Does that sound good?

Added this to the master list of frame additions/changes pre-launch at https://github.com/lookit/ember-lookit-frameplayer/issues/72 ("schedule": https://github.com/orgs/lookit/projects/2) 

Thank you especially for gathering feedback on this! That process is obviously important and greatly improves Lookit for everyone, but has been slightly outside the reach of our two-person team :)

**Comment by khamlin201** [comment]
Yes that sounds perfect! I'd say it's the only major concern our testers have had -- this will be a huge improvement!! Thanks so much :)

________________________________
