### ISSUE TITLE
Naming Video Outputs for certain trials and counter-balances? 

### ISSUE THREAD

**Issue by clementjxc** [lookit/ember-lookit-frameplayer#142]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to create a counter-balanced infant looking time study. When looking at the practice data I generated, I noticed that all the video file names can be difficult to understand from just looking at the video titles. 

**Is your feature request related to a particular frame?**
exp-lookit-video, (maybe random-parameter-set)

**Describe your idea or solution**
If my understanding is correct, it seems like the image type frames get to add some sort of id to identify the images used during testing. Adding something like that to the exp-lookit-video frame would allow us to better name which trial it was (ie. blue-help trial or green-help trial). Not sure if it's entirely feasible, but to allow us to also identify which set of parameter values in the random-parameter-set would generate which values for "response_conditions.0.conditionNum" in the data set. (I think I figured it out that the system counts from 0 onwards, but it's not entirely intuitive to me as a novice to this platform)

For example, my current trials in the randomizer are called "test-trials-clement" but rather than edittng this name, I would like to precisely name each frame that comes up in the randomizer (ie. blue-helpA, blue-helpB, green-helpA, green-helpB). 

**Describe alternatives you've considered**
A much more difficult solution would be to build some sort of UI that lets us specify what we want for the name of the output. Currently, I think I see the naming structure contains the response_uuid, study_uuid and frame sequence identifier (that's rather general, ie this problem). Maybe some sort of UI that lets us choose to add or remove additional fields that contribute to the naming of the output videos? 

**Additional context**
If your idea might be useful to other researchers too, do you have any questions for them about how they'd prefer it be implemented?

If applicable, a sketch of how your new frame should look or a marked-up screenshot showing how you want something to change is **super** helpful!

**Comment by kimberscott** [comment]
I think somehow giving researchers control over part of the video name is a very good idea - thanks for documenting this so clearly!

Just for concreteness, could you give an example of your randomizer frame definition (abridged if you want!), a resulting filename you currently see, and what you would like it to be?

If I understand correctly, a relatively straightforward way to do this would be to extend the base frame to take an optional custom video name parameter, which could then be subbed in in place of (part of) the frame sequence identifier. 

The possibly better, but slightly more involved (and less backwards-compatible) way to do it would be for most randomizers to take an object that looks more like the overall JSON 
```
{
  "frames": {
    "blue-help": {
      "kind": "exp-lookit-video",
      "color": "blue",
      ...
    },
    "green-help": {
       "kind": "exp-lookit-video",
       "color": "green",
       ...
    }
  },
  "sequence": ["blue-help", "green-help"]
}
```
instead of taking a list of unnamed frames like
```
[
  {
    "kind": "exp-lookit-video",
    "color": "blue",
    ...
  },
  {
     "kind": "exp-lookit-video",
     "color": "green",
     ...
  }
]
```
I'm not sure which will make more sense here; do you have any thoughts about which format would be more straightforward to understand? The former is more like the format you're using anyway for the overall JSON, but it'll introduce confusion about e.g. *which* blue-help we mean if there is also a higher-level blue-help frame. 

We actually probably don't want to make this specific to any particular frame type(s), as it'd disrupt the common standard pattern for video name generation. 

One advantage of having the frame sequence identifier in the video name is to make it easier to look up the appropriate frame data key from the video name, and the appropriate video name (prefix) from the data, for programmatic video processing. (This isn't necessarily anything "fancy" - e.g., you might go through programmatically and flag any video files that are missing,  or putting them in folders based on participant and/or condition. On the fancier but not machine-vision side, you might concatenate certain clips from the same session, or clip to the last N seconds, etc. for various coding needs.) So we'll want to consider any changes to the naming scheme in light of how that will work.

In many cases I think labs won't want information about the particular stimuli being shown to be in the filename, so as to keep blind coding blind. In those cases they may prefer to stick with the default filenames.

**Comment by clementjxc** [comment]
Hey Kim!

sorry this took a while, but here's my frame:
        "test-trials-clement": {
            "kind": "choice",
            "sampler": "random-parameter-set",
            "frameList": [
                {
                    "sources": "VIDEO1",
                    "altSources": "ALTVIDEO1"
                },
                {
                    "sources": "VIDEO2",
                    "altSources": "ALTVIDEO2"
                },
                {
                    "sources": "VIDEO3",
                    "altSources": "ALTVIDEO3"
                },
                {
                    "sources": "VIDEO4",
                    "altSources": "ALTVIDEO4"
                },
                {
                    "sources": "VIDEO5",
                    "altSources": "ALTVIDEO5"
                }
            ],
            "parameterSets": [
                {
                    "VIDEO1": "green-demo",
                    "VIDEO2": "blue-demo",
                    "VIDEO3": "inter-trial",
                    "VIDEO4": "green-help",
                    "VIDEO5": "blue-help",
                    "ALTVIDEO1": "green-demo",
                    "ALTVIDEO2": "blue-demo",
                    "ALTVIDEO3": "inter-trial",
                    "ALTVIDEO4": "green-help",
                    "ALTVIDEO5": "blue-help"
                },
                {
                    "VIDEO1": "blue-demo",
                    "VIDEO2": "green-demo",
                    "VIDEO3": "inter-trial",
                    "VIDEO4": "blue-help",
                    "VIDEO5": "green-help",
                    "ALTVIDEO1": "blue-demo",
                    "ALTVIDEO2": "green-demo",
                    "ALTVIDEO3": "inter-trial",
                    "ALTVIDEO4": "blue-help",
                    "ALTVIDEO5": "green-help"
                }
            ],
            "commonFrameProperties": {
                "kind": "exp-lookit-video",
                "baseDir": "
https://childdevelopment.psych.ubc.ca/lookit-hosting/",
                "testCount": 1,
                "audioTypes": [
                    "ogg",
                    "mp3"
                ],
                "pauseAudio": "pause",
                "videoTypes": [
                    "webm",
                    "mp4"
                ],
                "attnSources": "attention-grabber",
                "introSources": [],
                "musicSources": [],
                "unpauseAudio": "return_after_pause",
                "announceLength": 3,
                "calibrationLength": 0,
                "calibrationPositions": [
                    "left",
                    "right",
                    "left",
                    "right",
                    "center"
                ],
                "calibrationAudioSources": "chimes",
                "calibrationVideoSources": "attention-grabber"
            }
        }
    },

I was thinking about this for a little bit ,and maybe adding an optional
sub-field? Maybe something like this:

              "parameterSets": [
                {
                    "VIDEO1": "green-demo",

                    "VIDEO2": "blue-demo",
                    "VIDEO3": "inter-trial",
                    "VIDEO4": "green-help",

  "video-output": "green-help-A"

                    "VIDEO5": "blue-help",

  "video-output": "blue-help-A"

                    "ALTVIDEO1": "green-demo",
                    "ALTVIDEO2": "blue-demo",
                    "ALTVIDEO3": "inter-trial",
                    "ALTVIDEO4": "green-help",
                    "ALTVIDEO5": "blue-help"
                },
                  {
                    "VIDEO1": "blue-demo",
                    "VIDEO2": "green-demo",
                    "VIDEO3": "inter-trial",
                    "VIDEO4": "blue-help",

"video-output": "blue-help-B"

                    "VIDEO5": "green-help",

"video-output": "green-help-B"

                    "ALTVIDEO1": "blue-demo",
                    "ALTVIDEO2": "green-demo",
                    "ALTVIDEO3": "inter-trial",
                    "ALTVIDEO4": "blue-help",
                    "ALTVIDEO5": "green-help"
                }
            ],

If it wasn't painfully clear, I am really really new to JSON so I'm fairly
certain that this syntax is incorrect, but the goal would be so I can have
an output that would look something like this:

videoStream_1a79b103-1fe4-4daa-b0bf-4a932f5588ce_5-test-trials-clement_dba14e27-5f1c-4beb-a4ff-b21ae3bb0d85_1587604799035_849_
*green-help-A.*mp4


I just copied one of the exports and added the "video-output" field at the
end, appending to the existing syntax. All the other pieces of info that
are already naturally built into the video file is great (I think the
syntax of how these names are constructed should be added to the
documentation somewhere as well!) Alternatively, adding it to the beginning
would make it easier to sort once researchers download all the files since
most people would sort the files alphabetically!

This suggested setup would also allow me to preserve the randomization so I
can keep it random but to also be able to separate the videos between
conditions and trials (ie. green-help-A in one condition, green-help-B in
another condition).

Taking your concerns into considerations about researchers and blindness to
conditions, I would assume that whether researchers would want to keep the
videos blind (ie. not naming per condition) would be up to them in this
format? They could fill in the field "video-output" with names that are
still neutral like "1A" rather than "green-help-A" but it can still give
customisable options for researchers to develop a code for which condition
had which trial first (which is important for us) and to sort the videos
without opening each one into separate groups.

Please let me know if I missed anything!

Thanks!

Clement

**Comment by clementjxc** [comment]
Sorry if this is a repeat, but I realized I didn't hit reply all, so I
wasn't sure if this made it to you Kim!

Hey Kim!

sorry this took a while, but here's my frame:
        "test-trials-clement": {
            "kind": "choice",
            "sampler": "random-parameter-set",
            "frameList": [
                {
                    "sources": "VIDEO1",
                    "altSources": "ALTVIDEO1"
                },
                {
                    "sources": "VIDEO2",
                    "altSources": "ALTVIDEO2"
                },
                {
                    "sources": "VIDEO3",
                    "altSources": "ALTVIDEO3"
                },
                {
                    "sources": "VIDEO4",
                    "altSources": "ALTVIDEO4"
                },
                {
                    "sources": "VIDEO5",
                    "altSources": "ALTVIDEO5"
                }
            ],
            "parameterSets": [
                {
                    "VIDEO1": "green-demo",
                    "VIDEO2": "blue-demo",
                    "VIDEO3": "inter-trial",
                    "VIDEO4": "green-help",
                    "VIDEO5": "blue-help",
                    "ALTVIDEO1": "green-demo",
                    "ALTVIDEO2": "blue-demo",
                    "ALTVIDEO3": "inter-trial",
                    "ALTVIDEO4": "green-help",
                    "ALTVIDEO5": "blue-help"
                },
                {
                    "VIDEO1": "blue-demo",
                    "VIDEO2": "green-demo",
                    "VIDEO3": "inter-trial",
                    "VIDEO4": "blue-help",
                    "VIDEO5": "green-help",
                    "ALTVIDEO1": "blue-demo",
                    "ALTVIDEO2": "green-demo",
                    "ALTVIDEO3": "inter-trial",
                    "ALTVIDEO4": "blue-help",
                    "ALTVIDEO5": "green-help"
                }
            ],
            "commonFrameProperties": {
                "kind": "exp-lookit-video",
                "baseDir": "
https://childdevelopment.psych.ubc.ca/lookit-hosting/",
                "testCount": 1,
                "audioTypes": [
                    "ogg",
                    "mp3"
                ],
                "pauseAudio": "pause",
                "videoTypes": [
                    "webm",
                    "mp4"
                ],
                "attnSources": "attention-grabber",
                "introSources": [],
                "musicSources": [],
                "unpauseAudio": "return_after_pause",
                "announceLength": 3,
                "calibrationLength": 0,
                "calibrationPositions": [
                    "left",
                    "right",
                    "left",
                    "right",
                    "center"
                ],
                "calibrationAudioSources": "chimes",
                "calibrationVideoSources": "attention-grabber"
            }
        }
    },

I was thinking about this for a little bit ,and maybe adding an optional
sub-field? Maybe something like this:

              "parameterSets": [
                {
                    "VIDEO1": "green-demo",

                    "VIDEO2": "blue-demo",
                    "VIDEO3": "inter-trial",
                    "VIDEO4": "green-help",

  "video-output": "green-help-A"

                    "VIDEO5": "blue-help",

  "video-output": "blue-help-A"

                    "ALTVIDEO1": "green-demo",
                    "ALTVIDEO2": "blue-demo",
                    "ALTVIDEO3": "inter-trial",
                    "ALTVIDEO4": "green-help",
                    "ALTVIDEO5": "blue-help"
                },
                  {
                    "VIDEO1": "blue-demo",
                    "VIDEO2": "green-demo",
                    "VIDEO3": "inter-trial",
                    "VIDEO4": "blue-help",

"video-output": "blue-help-B"

                    "VIDEO5": "green-help",

"video-output": "green-help-B"

                    "ALTVIDEO1": "blue-demo",
                    "ALTVIDEO2": "green-demo",
                    "ALTVIDEO3": "inter-trial",
                    "ALTVIDEO4": "blue-help",
                    "ALTVIDEO5": "green-help"
                }
            ],

If it wasn't painfully clear, I am really really new to JSON so I'm fairly
certain that this syntax is incorrect, but the goal would be so I can have
an output that would look something like this:

videoStream_1a79b103-1fe4-4daa-b0bf-4a932f5588ce_5-test-trials-clement_dba14e27-5f1c-4beb-a4ff-b21ae3bb0d85_1587604799035_849_
*green-help-A.*mp4


I just copied one of the exports and added the "video-output" field at the
end, appending to the existing syntax. All the other pieces of info that
are already naturally built into the video file is great (I think the
syntax of how these names are constructed should be added to the
documentation somewhere as well!) Alternatively, adding it to the beginning
would make it easier to sort once researchers download all the files since
most people would sort the files alphabetically!

This suggested setup would also allow me to preserve the randomization so I
can keep it random but to also be able to separate the videos between
conditions and trials (ie. green-help-A in one condition, green-help-B in
another condition).

Taking your concerns into considerations about researchers and blindness to
conditions, I would assume that whether researchers would want to keep the
videos blind (ie. not naming per condition) would be up to them in this
format? They could fill in the field "video-output" with names that are
still neutral like "1A" rather than "green-help-A" but it can still give
customisable options for researchers to develop a code for which condition
had which trial first (which is important for us) and to sort the videos
without opening each one into separate groups.

Sorry if this wasn't clear either, but part of the problem I'm trying to
solve as well is to help my team identify which video the infants saw
during the trials. We're using a violation of expectations paradigm so it's
crucial we know which side our 3rd actor chose to help, and where babies
are looking. Based on the audio component from what we hear of our study
and the reaction of the participants, this would be virtually impossible
because the study sounds near identical. This is to replace our typical
methods of having an RA live code as participants are running through the
study and are able code immediately for which condition and for how long
they looked at.

Please let me know if I missed anything!

Thanks!

Clement

Clement J. X. Choi
B.Sc, Behavioural Neuroscience
University of British Columbia
Cell: (778) 688 8362

**Comment by kimberscott** [comment]
Thank you - this is super helpful! Will need to think a little more about where in the filename will cause least disruption (and what restrictions are necessary for security/filesystems reasons - e.g. we can't allow arbitrary characters or lengths for the labels) but I suspect your proposal will make most sense.


> All the other pieces of info that
> are already naturally built into the video file is great (I think the
> syntax of how these names are constructed should be added to the
> documentation somewhere as well!)

There's a short description here: https://lookit.readthedocs.io/en/develop/researchers-experiment-data.html#viewing-all-study-videos - if you're up for highlighting that info more (own heading maybe?) or putting it someplace that makes more sense to you, PRs to the docs are very welcome. 

> Sorry if this wasn't clear either, but part of the problem I'm trying to
> solve as well is to help my team identify which video the infants saw
> during the trials. We're using a violation of expectations paradigm so it's
> crucial we know which side our 3rd actor chose to help, and where babies
> are looking. Based on the audio component from what we hear of our study
> and the reaction of the participants, this would be virtually impossible
> because the study sounds near identical. This is to replace our typical
> methods of having an RA live code as participants are running through the
> study and are able code immediately for which condition and for how long
> they looked at.

Ooh, this actually has a simpler answer in the meantime. The exp-lookit-video frame stores which videos were presented (see `videosShown` in the "Data collected" tab here: https://lookit.github.io/ember-lookit-frameplayer/classes/Exp-lookit-video.html In general the expected workflow involves making use of the CSV data you can download, separate from the video. Sorry, I didn't realize you were concerned there was *no* way to tell what video was being played when - that would be a critical thing to fix! This is still likely worth doing, imo, to make coding more convenient, but let me know if you think having the info in the CSV makes the filename customization unnecessary.

**Comment by kimberscott** [comment]
Closing as there's a reliable way to match session data to video filenames, so the motivation for this issue is addressed - feel free to reopen if you feel it'd be helpful, beyond that, to have more control over filenames.
