### ISSUE TITLE
Documentation doesn't match "kind" for Exp-lookit-images-audio (solved but not sure how to update code)

### ISSUE THREAD

**Issue by mpelz** [lookit/ember-lookit-frameplayer#150]
**Describe the bug**
This frame works well when properly referred to, but when defining the "kind" in the frame inside of a study, it needs to be defined as "exp-lookit-image-audio" (image singular rather than images plural). I went to change it on the frameplayer page, but realized that that would most likely require changes to many parts of the internal code, and that it would most likely be easier to update the list of acceptable frame classes to include the plural rather than the singular but I'm not sure where in the Lookit code it's checking to see what is a valid "kind". If you can point me to where I can do that I'm happy to update it myself or if the first thing I mentioned is the right thing to do I can submit that as well. 

**Which frame or frames does it affect?**
exp-lookit-images-audio

**Example**
Link to your study (draft) where this problem occurs, if applicable: https://lookit-staging.mit.edu/exp/studies/324/

**To Reproduce**
Steps to reproduce the behavior (edit the example below):
1. Go to staging-lookit.cos.io/exp and log in as an experimenter.
2. Create a study by copying the documentation on the page of exp-lookit-images-audio (or define that frame kind in any study). Build preview dependencies. (OR view our study at https://lookit-staging.mit.edu/exp/studies/324/)
4. Click 'preview' from the study edit page
5. See that it fails to load (note: if you change it to exp-lookit-**image**-audio then it does load!

**Expected behavior**
The frame should load and exp-lookit-images-audio should be listed as an acceptable frame type. 

**Environment (please complete):**
 - Lookit environment (production, staging, local + previewing or participating in study): previewing
 - Version of frameplayer code (`last_known_player_sha field` on the study edit page): 2903a9a08ee1a84a7963fac8ade3f5eb980cb6e4
 - Operating system [e.g. Windows, Mac, Linux]: Mac
 - Browser [e.g. Chrome, Firefox, Safari] and version: Chrome

**Additional information**

If we have trouble reproducing the bug with this information, we'll likely ask for the following additional information:
 - Webcam used [built-in or external]:
 - Monitor used [laptop monitor or external and resolution]: 
 - Upload and download speed [using e.g. https://www.speedcheck.org/]: 
 - How many times have you been able to reproduce the error using the steps above? How many times have you seen the expected behavior? 

If you have tried to reproduce this bug under multiple circumstances, please note everything you have tried. For instance, perhaps this happens in BOTH Chrome and Firefox on your Mac, and in Chrome but not Firefox on your Windows machine.

[Here is a great article from a grumpy programmer where you can learn more about writing excellent bug reports.](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

**Comment by kimberscott** [comment]
I am really sorry because this is an amazing bug report (and how did you even realize exp-lookit-image-audio worked?) but I think you just need to [update the experiment runner version](https://lookit.readthedocs.io/en/develop/researchers-update-code.html) to the latest. The commit you have is from an intermediate state where there actually was an exp-lookit-image-audio frame (and a bunch of others) that all got absorbed into a single exp-lookit-images-audio. Let me know if that doesn't fix it?

**Comment by mpelz** [comment]
Ah that did fix it, thanks for your help! Should've tried that before I sent this, but I'll close the issue now. Oh, and I figured it out because I saw "image" in the list of acceptable frames in developer tools. At least I know how to submit a bug report now!
