### ISSUE TITLE
Adding "pause/return" feature for exp-lookit-images-audio

### ISSUE THREAD

**Issue by schang198** [lookit/ember-lookit-frameplayer#151]
For the exp-lookit-images-audio frame, I would like to add a pause/return feature similar to the one in the exp-lookit-preferential-looking frame, where it stops the study and gives the parent a few moments to turn around again before resuming. It would be ideal to have options upon return for 1) restarting the interrupted trial, 2) moving to an alternate set of stimuli, or 3) continuing to the next trial.

**Comment by kimberscott** [comment]
Looks like we can combine this with #152 - can you and @kc3922 check that there's a way to do this that would satisfy at least both of your use cases?

**Comment by kimberscott** [comment]
(just closing in favor of #152, this is still very much on the list!)

**Comment by kc3922** [comment]
Sounds good! Thanks for the update!
