### ISSUE TITLE
Pause-Resume/Restart Button

### ISSUE THREAD

**Issue by kc3922** [lookit/ember-lookit-frameplayer#152]
We received feedback from a number of participants suggesting a pause button might be helpful for when their child gets too fussy to continue. However, due to the nature of our study, this would need to be some sort of pause-resume/restart button that would take them to the beginning of all of the trial frames for that section. Specifically, I'm looking to see if this could be implemented for the exp-lookit-story-page frames.

I was thinking that it might be helpful to have a pause-resume/restart button so that it could be applicable to a number of different studies. One option would be to pause and resume an individual exp-lookit-story-page frame, another would be to pause and restart an individual exp-lookit-story-page frame, and (for our purposes) another option would be to pause and restart from the beginning of a group of exp-lookit-story-page frames that are grouped under one section of the study. I was thinking the pause and resume/restart buttons could be separate so that a researcher could customize the button options. I attached images that I hope make this a bit more clear (Sorry for how crude they are!).

I would love to hear any and all ideas of exactly how this could be implemented or designed to better serve the needs of all Lookit researchers! 

![pause-restart](https://user-images.githubusercontent.com/59930859/87182810-dc0c9200-c2b2-11ea-9083-3d47e9b61b1b.png)

![pause-resume](https://user-images.githubusercontent.com/59930859/87182910-124a1180-c2b3-11ea-8ddb-358f11959a6a.png)

**Comment by kimberscott** [comment]
The `exp-lookit-images-audio` frame has subsumed the more specific `exp-lookit-story-page` frame, so we'd likely implement pause/restart functionality there. So it sounds like this is in the same spirit as https://github.com/lookit/ember-lookit-frameplayer/issues/151 and could be merged with that if you agree on how you'd want this to work?

**Comment by schang198** [comment]
Hi, this seems to be exactly what I would also like to have in my study! I am using the `exp-lookit-images-audio` frame and would also prefer to be able to pause and restart from the beginning of a group of frames that belong together in a section. 

I mentioned in my separate post  (#151 ) that the appearance/functionality might be similar to the pause option in `exp-lookit-preferential-looking`, which allows the researcher to set an attention-grabber image when the page is paused, an audio track for "study paused", and another audio track for "return to study" with a few seconds built-in to allow the parent to turn around again.

**Comment by kc3922** [comment]
Hello! Yeah that sounds like a great idea. I think an attention-grabber image when the page is paused would be interesting. For our study we're trying to have the children look at the parent and not the screen though, so I'm not exactly sure if that aspect would work for our purposes. Would it be possible to have the page be blank and add in the attention grabber/audio track as an option?

**Comment by schang198** [comment]
Hello! So it seems that we're in agreement about the main functionality, which is to pause on a key press and then return to the start of a group of frames. It doesn't matter for my study what the paused page itself looks like, so blank or attention-grabber as an option would both be fine. After chatting on Slack, it seems we are also both looking to have the "return to study" option include an audio track/countdown ("3, 2, 1, action!" like the existing version in `exp-lookit-preferential-looking`) before restarting the trial (to allow the parent to turn back around/etc). @kimberscott What would the next steps be for getting this implemented? Do you need any further detail from us about the design? Thanks so much!

**Comment by kimberscott** [comment]
This sounds good! I'll let you know if I have questions as I get started, but suspect this is enough to draft something to run by you. It's on my list at https://github.com/orgs/lookit/projects/2 - I'm just dealing with making randomization more flexible first (accepting a Javascript function to generate the protocol) because that's currently a hard blocker for several people.

**Comment by kimberscott** [comment]
Will merge this with #41 - may be simplest to implement as a mixin that most frames use, where you can specify button to pause, image/video, pause/unpause audio, and what frame to go to upon unpausing (default same one).

**Comment by kimberscott** [comment]
Just an update - have an outline of how this will work, it turned out to involve first addressing #48 because you'll be looping back to previous frames.

**Comment by kc3922** [comment]
Sounds good! Thanks for the update :)
