### ISSUE TITLE
Hide stimuli and display "uploading" message during video upload at end of frame

### ISSUE THREAD

**Issue by UCDOakeslab** [lookit/ember-lookit-frameplayer#156]
**Is your feature request related to a problem? Please describe.**
I recently discovered that when participants' have slow internet (particularly when their upload speed is low, e.g.. ~1mbps) their individual videos upload shorter than expected. For example, when I test the videos with strong upload speeds (around 4-5 mbps) then the videos for my trials should be around 11-12 s long. Most of our participants' videos are the expected length.

Kim told me that in the case where someone has slow internet upload speed, you can adjust the maxUploadSeconds parameter and set it to a longer value. The default is 5 s. I tested this solution by using the Network Link Conditioner app (I'm on a Mac) that allows you to simulate slower internet connections (https://nshipster.com/network-link-conditioner/)

Using a slower internet connection (1mbps upload speed) I was able to confirm that yes, a slower upload speed does result in cut off/shorter-than-expected videos of participants, or data loss.

Here is my question: When I changed the maxUploadSeconds = 10 and tested this with slow internet (1 mbps upload), I was able to upload my entire video (yay!). However, what ended up happening was that because I'm essentially slowing down the experiment, the images that should only be on the screen for 8 s remained on the screen for much longer than 8 s. This is problematic because this means that babies that have strong WiFi are experiencing the experiment differently than babies with slow WiFi. 

Is there any way to force the images to go away after a certain amount of time has passed but still "stall" the experiment to let the videos finish uploading to the server in the case of slow internet speeds?

**Is your feature request related to a particular frame?**
exp-lookit-preferential-looking

**Describe your idea or solution**
Kim suggested a great idea on Slack. I will paste that here: 
Not yet, I’m sorry! That’s a really good idea though - are you up for making a feature request here? I think we could set up so that (optionally) upon trying to proceed to the next frame, the frame goes blank or just displays “uploading video, please wait…“. In the meantime, the workaround depends on the frame you’re using. For video, I think you could add a single blank frame to the end of the video and that’s what it would freeze on, although that would be annoying if you’re looping it. For exp-lookit-images-audio, if you happen to have fixed-length trials (rather than waiting for the user to click) you could make your own “uploading video, please wait” image, and tell it to appear at a delay of the trial length and fill the screen.

**Describe alternatives you've considered**
See above.

**Additional context**
I think the would be widely used because slow internet connections are somewhat common. 

If applicable, a sketch of how your new frame should look or a marked-up screenshot showing how you want something to change is **super** helpful!
As Kim mentioned, we could design our own image that would be presented on the screen, or really just simple text would be great too. Something that just says, "please wait...your data is being uploaded to our secure server...".

**Comment by kimberscott** [comment]
Now available in dev branch (copy commit ID from https://github.com/lookit/ember-lookit-frameplayer/commits/develop). 

You can set whether to show a placeholder while starting recording and while uploading; text and background color for each; (shared) image or video. See parameters at e.g. https://lookit.github.io/lookit-frameplayer-docs/classes/Exp-lookit-images-audio.html - showWaitForUploadMessage, waitForUploadMessageColor, etc.
