### ISSUE TITLE
Modify exp-lookit-change-detection so 1) image streams can also show video and 2) display time can be set to differ for each image category

### ISSUE THREAD

**Issue by inichoso** [lookit/ember-lookit-frameplayer#183]
I tried to edit this frame on my own but as I have no experience with JSON, I was unsuccessful. I would like the exp-lookit-change-detection frame to be modified so that "leftImagesA", "leftImagesB", "rightImagesA", and "rightImagesB" are capable of playing video files in addition to just still jpeg files. Also, I would also like to have the ability to make different stream categories display for different lengths of time. Basically, instead of just one "displayMs", I would like to have "displayMsLeftImagesA", "displayMsLeftImagesB", etc. which would allow me to set specific display times for specific image types. 

Thank you so much! I really appreciate this!

**Comment by kimberscott** [comment]
(Just FYI this is in progress now!)

**Comment by kimberscott** [comment]
This is now available on the dev branch! 

* You can update the experiment runner to version `20af5ca74ee0fb4a718b1d7618759f8b942270ab` to use the update (list of commits/versions of develop branch is at https://github.com/lookit/ember-lookit-frameplayer/commits/develop). 
* See the [develop branch docs](https://lookit.readthedocs.io/projects/frameplayer/en/develop/components/exp-lookit-change-detection/doc.html#example) for the updated syntax for this frame. (All previous functionality is preserved.)

Once you try it let me know if you run into any issues!

**Comment by kimberscott** [comment]
Closing this for now, feel free to reopen if you run into any problems!

**Comment by inichoso** [comment]
This is great Kim! Thank you so much!
