### ISSUE TITLE
exp-look-exit-survey can't add blocks e.g. documentation example doesn't work.

### ISSUE THREAD

**Issue by InfantLab** [lookit/ember-lookit-frameplayer#203]
I wanted to add blocks to my exit page but i couldn't get it to work. Even the example given in the documentation doesn't work
https://lookit.readthedocs.io/projects/frameplayer/en/develop/components/exp-lookit-exit-survey/doc.html

**Example**
I was trying this in https://lookit.mit.edu/exp/studies/317 but it's not currently there as I've put in a workaround. 

**To Reproduce**
Steps to reproduce the behavior (edit the example below):
1. Use the following code as the exit page for a study
```
"my-exit-survey": {
    "kind": "exp-lookit-exit-survey",
    "debriefing": {
        "title": "Thank you!",
        "blocks": [
            {
                "text": "THIS IS ALL JUST PLACEHOLDER DEBRIEFING TEXT. SEE DOCS FOR ADVICE ON WHAT TO INCLUDE HERE.",
                "listblocks": [
                    {
                        "text": "Suscipit adipiscing bibendum est ultricies integer quis auctor."
                    },
                    {
                        "text": "Imperdiet sed euismod nisi porta lorem mollis."
                    },
                    {
                        "text": "Sollicitudin tempor id eu nisl nunc mi."
                    }
                ]
            },
            {
                "title": "Nulla porttitor",
                "image": {
                    "src": "https://www.mit.edu/~kimscott/placeholderstimuli/img/apple.jpg",
                    "alt": "Sample image your child saw of an apple"
                }
            },
            {
                "title": "Your gift card will arrive in 2-3 days",
                "text": "Suscipit adipiscing bibendum est ultricies integer quis auctor."
            }
        ]
    }
}
```

2. Proceed through the study until you reach the frame above.
3. The exit page just shows the header "Thank you!"

**Expected behavior**
Listblocks are working in other frame types but not exp-lookit-exit-survey.

**Environment (please complete):**
 - Lookit environment (production, previewing): production
 - Version of frameplayer code (`last_known_player_sha field` on the study edit page): 08c87853e2a05704c75d8d8c2460e2fc758de2e1
 - Operating system [e.g. Windows, Mac, Linux]: Windows
 - Browser [e.g. Chrome, Firefox, Safari] and version: Firefox

**Additional information**
None

**Comment by kimberscott** [comment]
It looks like you're using version 2.2.0 and just need to update to >=2.2.1 (see [release notes](https://github.com/lookit/ember-lookit-frameplayer/releases)) - can you let me know if this works using the latest version?

(The docs are correspondingly versioned - at the link you included you can see a little note at the top, 
![Screen Shot 2020-12-18 at 10 45 35 AM](https://user-images.githubusercontent.com/9554627/102633296-3ccfae80-411e-11eb-9b36-e855014a0cc5.png)

If you scroll down to the bottom and click on "develop" you'll see options to look at the docs for other versions.)

**Comment by InfantLab** [comment]
Ah, yes, that fixes it. Thanks,
