### ISSUE TITLE
Customise audio for "lookawayTone" in "exp-lookit-video-infant-controlled" frame

### ISSUE THREAD

**Issue by frabiancolain95** [lookit/ember-lookit-frameplayer#215]
**Is your feature request related to a problem? Please describe.**
Currently, there are only 3 audio options for the "lookawayTone" in the "exp-lookit-video-infant-controlled" frame, which are either ‘tone’ (A 220), ‘noise’ (pink noise), or ‘none’. None of the audios seem very infant-friendly. 

**Is your feature request related to a particular frame?**
[E.g., exp-lookit-video-infant-controlled]

**Describe your idea or solution**
It would be great if researchers could customise the audios to be used as "lookawayTone" in this frame to allow for more infant-friendly and personalised tones. Thank you.

**Comment by kimberscott** [comment]
Addressed by #244
