### ISSUE TITLE
Stop audio of "waitForUploadVideo" from continuing into test video

### ISSUE THREAD

**Issue by frabiancolain95** [lookit/ember-lookit-frameplayer#217]
**Is your feature request related to a problem? Please describe.**
When using the "waitForUploadVideo" parameter, the specified video cannot currently have an associated audio, as its audio continues into the test video.

**Is your feature request related to a particular frame?**
video-record mixin

**Describe your idea or solution**
It would be great if researchers could include a "waitForUploadVideo" with an audio, without the audio continuing into the test video. Thank you.

**Describe alternatives you've considered**
I can make the "waitForUploadVideo" & associated audio very short, however, this may be a bit accurate given that videos take a different time to upload sometimes.

**Comment by frabiancolain95** [comment]
This happens also from the Pause Video to the Test Video - the pause video cannot currently have any audio, otherwise, it will continue for the whole session and play also during the test trials. It would be great if researchers could include an audio in the Pause Audio, without the audio continuing into the test videos (this was possible with earlier exp runners). Thank you

**Comment by kimberscott** [comment]
Added in v2.3.0! https://github.com/lookit/ember-lookit-frameplayer/releases/tag/v2.3.0 

You can just update the code to the latest version to use these changes.
