### ISSUE TITLE
Consent document sections not populating

### ISSUE THREAD

**Issue by amanis10** [lookit/ember-lookit-frameplayer#222]
Hi! I'm having some trouble with my consent document. I am using consent_003, as this is the format that we submitted for IRB approval. When I preview the study, the headings for "benefits, risks, and payment" as well as "rights of research subjects" appear, but the text underneath them does not. Someone suggested updating the experiment runner so I did that but it is still not working. Any ideas on how to fix this? Thanks!

**Comment by kimberscott** [comment]
Can you share the relevant frame definition from your study protocol so that we can reproduce this?

**Comment by amanis10** [comment]
Thank you! This is what I have my configuration.
 "video-consent": {
            "gdpr": false,
            "kind": "exp-lookit-video-consent",
            "template": "consent_003",
            "PIName": "Sudha Arunachalam",
            "institution": "New York University",
            "Online Parental Consent Form, IRB-FY2018-2041 ": "You are being invited to take part in a research study to learn more about how children learn to  understand language. Your participation is voluntary which means you can choose whether or  not you want to take part in this study. Researchers led by Dr. Sudha Arunachalam at the  Communicative Sciences and Disorders department at the Steinhardt School of Culture,  Education, and Human Development at New York University are running this study on Lookit.",
            "purpose": "The purpose of this study is to understand how toddlers and preschoolers learn language.  Learning their first language is one of the most amazing achievements of early childhood and  we are interested in learning how children accomplish it. ",
            "procedures": "This study takes about approximately 15 minutes to complete. Your child will watch short  videos and play a game with us. This session will be video recorded and you may review these  recordings and request that all or any portion of the recordings be destroyed.",
            "participation": "You and your child are free to choose whether to be in this study. If you and your child choose  to participate, it's okay to stop at any point during the session. Please pause or stop the session  if your child becomes very fussy or does not want to participate!",
            "benefits, risks, and payment": "You will receive a $10 gift card for your participation. If you or your child withdraws, you will  still receive full payment. The main risk of allowing us to use and store your information for research is a potential loss of  privacy. We will protect your privacy by labeling your information with a code rather than your  or your child’s name, and keeping the key to the code in a password-protected computer.You are not expected to get any benefit from being in this research study.",
            "data collection and webcam recording": "During the session, you and your child will be recorded via your computer's webcam and microphone. At the end of the session, you will be prompted to choose a privacy level for your  webcam recordings. You will have the option to withdraw your video data at this point. Video  recordings and other data you enter are sent securely to the Lookit platform and stored  indefinitely. You can view your past recordings on Lookit under Studies -> Your past studies  at any time. Data is stored securely on Lookit servers and by researchers. However, there is  always a small risk that data transmitted over the internet may be intercepted or that the  security of stored data may be compromised. No video clips will be published or shared unless you allow this when selecting a privacy level. If  we do not receive a consent recording (the video you'll make to the right) for this session and  cannot verify that you agreed to participate, no other video from your session will be viewed." ,
            "use of data by study researchers": "The research group led by Dr. Sudha Arunachalam at New York University will have access to  video and other data collected during this session. We will also have access to your account  profile, demographic survey, and the child profile for the child who is participating, including  changes you make in the future to any of this information. We may study your child's responses  in connection with his or her previous responses to this or other studies run by our group,  siblings' responses to this or other studies run by our group, or demographic survey responses.",
            "use of data by lookit": "Because this study is being run on the Lookit platform, researchers working on the Lookit  project at MIT will also have access to the data collected during this session, in addition to your  account data, child profiles, and demographic survey responses. This data may be used by  Lookit to detect and fix technical problems or identify new features that would be helpful;  provide support to study researchers; assess data quality (for instance, how well an observer  can tell which direction children are looking); evaluate the site's success in reaching a diverse  population; and characterize family engagement (for instance, looking at what aspects of a  study make parents more interested in coming back later).",
            "publication of results": "The results of the research may be presented at scientific meetings or published in scientific  journals. Raw data (for instance, looking times to the left and right of the screen) may be  published when it cannot identify children. We never publish children's birthdates or names,  and we never publish your demographic data in conjunction with your child's video.",
            "rights of research subjects": "For questions about your rights as a research participant, you may contact the University  Committee on Activities Involving Human Subjects, New York University, 665 Broadway, Suite  804, New York, NY 10012 at (212) 998-4808 or ask.humansubjects@nyu.edu.",
            "researcher contact information": "If there is anything about the study or your participation that is unclear or that you do not  understand, or if you have questions or wish to report a research-related problem, you may  contact Dr. Sudha Arunachalam at (212) 998-5230 or sudha@nyu.edu. In the very unlikely  event of a research-related injury, please contact 911 and Dr. Sudha Arunachalam. If you or your child have any questions or concerns about the Lookit platform, please contact  Kim Scott at kimscott@mit.edu or 617 324 4859. "
        },

**Comment by kimberscott** [comment]
Ohh, I see - the issue here is that the parameters need to be as listed in the documentation at https://lookit.readthedocs.io/projects/frameplayer/en/latest/components/exp-lookit-video-consent/doc.html#parameters. For instance, there is no `benefits, risks, and payment` parameter but there is a `payment` parameter. 

You should actually be seeing some informative error messages showing up about missing parameters as in [this section of the tutorial](https://lookit.readthedocs.io/en/develop/tutorial-first-study.html#using-the-javascript-console-in-your-browser-to-learn-more-about-any-problems).

There's a lot of text here that you actually do not need to provide to the consent frame - to see how everything fits together you can take a look at the [template](https://github.com/lookit/research-resources/blob/master/Legal/Lookit%20consent%20form%20template%203.md). You only specify the pieces that are shown there in brackets, and only with those exact names.
