### ISSUE TITLE
missing data in json file

### ISSUE THREAD

**Issue by SbllDtrch** [lookit/ember-lookit-frameplayer#226]
**Describe the bug**
The data associated with some frames is not recorded in the json result file despite the frames being played.

**Which frame or frames does it affect?**
exp-looing-start-recording; exp-lookit-stop-recording; exp-lookit-images-audio

**Example**
https://lookit.mit.edu/exp/studies/367/
This is a series of preferential looking trials each composed of 5 frames (a first exp-looing-start-recording frame, 3 exp-lookit-images-audio;  and 1 exp-lookit-stop-recording). We do a session recoding for each trial.
10 participants piloted this study, the number of missing frames in their individual json files varies from 0 to 23 ({1, 1, 23, 0, 1, 0, 0, 1, 0, 0}).
This is a screenshot of the json file of participant/response af4e1892-0f30-4d2a-b2e7-913785da5c5c who had 23 missing frames:

![Screen Shot 2021-02-15 at 10 44 24](https://user-images.githubusercontent.com/3780236/107932440-db8d5580-6f7d-11eb-9267-9f8e66c466ec.png)

55-block1B-0 is the first frame of a trial and 60-block1B-5 is the last frame (so this is a correctly recorded trial with 5 frames).
But the next trial, i.e., 61-block1B-0, there are 3 missing frames: 
64-block1B-3
65-block1B-4 
66-block1B-5
despite the participant having seen them all (from the video length, sound and reaction of the baby; videoStream_12ddb152-7d0f-409e-9f55-deabf523522c_61-block1B-0-multiframe_af4e1892-0f30-4d2a-b2e7-913785da5c5c_1611504306532_91)
 

**To Reproduce**
On my configuration (see below) I can reproduce the error almost each time I run the study although not at the extend of the participant described above (I can get 0-1-2 missing frames for the whole study much like other participants). But the exact location of error varies: it is not a specific trial that triggers it, nor a specific frame (it can be any of the 5 frames used in the trial sequence, and it can be one frame or several of them)

**Expected behavior**
All data should be recorded in the json file

**Screenshots**
On one of my test (json: Logic-for-babies_47eefe7b-b7cb-4c71-83d7-ccbdf8f517b0_frames)
"122-block2-4",
"123-block2-5",
"125-block2-1",
"126-block2-2",
"127-block2-3",

Frame 124-block2-0 is missing (exp-lookit-start-recording) 

This is what the console looks like at that time:

<img width="1059" alt="Screen Shot 2021-02-15 at 10 26 43" src="https://user-images.githubusercontent.com/3780236/107932424-d6c8a180-6f7d-11eb-836a-4f36ef2e9272.png">

**Environment (please complete):**
 - Lookit environment : production, preview & participating
 - Version of frameplayer code : 963c2ec867a55dcd817f5fb9020839a2b291d126 
 
Mine:
 - Operating system [e.g. Windows, Mac, Linux]: Mac HighSierra 10.13.6
 - Browser [e.g. Chrome, Firefox, Safari] and version: Chrome 84.0.4147.105

Participant af4e1892-0f30-4d2a-b2e7-913785da5c5c 
 - Operating system [e.g. Windows, Mac, Linux]: Mac Mojave 10.14.6
 - Browser [e.g. Chrome, Firefox, Safari] and version: Chrome
 
**Additional information**

**Comment by kimberscott** [comment]
Thanks for documenting this so carefully! This is a priority to fix and I'm sorry data is going missing.

**Comment by kimberscott** [comment]
Just an update - I can reproduce this locally, have ruled out a few possible explanations, and have an idea what's going on (occasionally with short frames, saving one frame overlaps with saving another and one of the additions gets overwritten). I have one solution that works (waiting for save to complete before moving to next frame) but that would introduce a ~1s delay between all frames. 

I have another solution where frame data isn't dropped but it is possible for it to end up inserted out of order in the sequence - this is an improvement over the current situation but I'd ideally like to avoid that possibility too.

**Comment by kimberscott** [comment]
Fixed in release 2.3.2 (https://github.com/lookit/ember-lookit-frameplayer/releases/tag/v2.3.2)!
