### ISSUE TITLE
Rebase branch "pairs-games" against master

### ISSUE THREAD

**Issue by okaycj** [lookit/ember-lookit-frameplayer#283]
### Summary 
Carissa Aekin's branch is called "pairs-games", and it has a few custom frames that they made.  It just needs to have master merged into it to catch up with other recent changes.  

### Acceptance Criteria

* Please can you rename this branch "aekins_pairs-games"
* I don't expect any interesting conflicts, but in general their custom frames should be left but other changes should follow master branch
* Let us know what the new commit-SHA is! 

Original SHA: 36940395b9bd3bd7544962368955b151ca9fc9b6
New SHA: 32237c501e32351b711fe7ad3174385953a7ff2a

**Comment by mekline** [comment]
@okaycj can this be closed?

**Comment by okaycj** [comment]
> @okaycj can this be closed?

Yes.
