### ISSUE TITLE
Create bespoke branch for everde

### ISSUE THREAD

**Issue by okaycj** [lookit/ember-lookit-frameplayer#284]
### Summary 

The current commit is dbf10e4aa551057534cf24e9666fead2902f1ad4, and it has some existing changes to privacy language that she needed/needs to meet IRB requirements. 

### Acceptance Criteria

So to update this, I think we want to do the following:

- Create branch for this study called "everde_no-databrary".
- Merge master into this branch to catch any other updates. For conflicts, make sure that the changes to privacy settings in the bespoke version are retained/not over written with the regular ones. 
- Update the exit surveyframe to remove the section indicated in her screenshot below.
- Email me and Erica with the new hash!

<img width="600" alt="Screen Shot 2021-11-19 at 3 07 00 PM" src="https://user-images.githubusercontent.com/44074998/143059337-035ee0d4-70b1-4a44-8ec0-0fae5d3c120f.png">

**Comment by mekline** [comment]
@okaycj can this be closed?

**Comment by okaycj** [comment]
> @okaycj can this be closed?

I think so.
