### ISSUE TITLE
Freezing Experiments

### ISSUE THREAD

**Issue by okaycj** [lookit/ember-lookit-frameplayer#286]
**Describe the bug**
Experiments are freezing.  They will _sometimes_ not freeze if you try is over and over again. 

**Which frame or frames does it affect?**
Currently unsure of the exact frame, but by first example it where the browser begins recording.  

**Example**
1. https://lookit-staging.mit.edu/exp/studies/89/

**To Reproduce**
1. Open **Firefox** browser. (This issue does not present itself in Chrome or Edge.)
1. Go to https://lookit-staging.mit.edu/exp/studies/89/ (You may have to log in)
2. Click **Preview Study**
3. Select child from dropdown
4. Click **Preview Now!**
3. Breeze through setup and consent frames
4. Click next on explanation of study
5. Screen will read "Establishing video connection please wait...".  Green light for camera will be lit.  
6. User is unable to proceed. 

      
**Expected behavior**
Browser should properly detect that the video connection has been established and allow the user to proceed with the study.  

**Screenshots**
Here's the example screen that I get stuck on. 
<img width="1440" alt="Screen Shot 2022-01-19 at 11 43 32 AM" src="https://user-images.githubusercontent.com/44074998/150175961-15016dc3-5350-4819-a5b5-fc3ebe8948e1.png">

Here's the version of Firefox is am using.
<img width="779" alt="Screen Shot 2022-01-19 at 11 34 52 AM" src="https://user-images.githubusercontent.com/44074998/150176166-8f55fcd7-2ccf-4390-9ea3-5f17e499a382.png">

**Environment (please complete):**
 - Lookit environment (production, staging, local + previewing or participating in study):  Staging
 - Version of frameplayer code (`last_known_player_sha field` on the study edit page):  
 - Operating system [e.g. Windows, Mac, Linux]: Mac
 - Browser [e.g. Chrome, Firefox, Safari] and version: Firefox

**Additional information**
As mentioned above, this issue is only with Firefox.  ~I am convinced this is a race condition, but time will tell.~ It turns out that the issue has to do with improperly implemented promise.  The promise's resolve/reject functions are stored on the recorder's class.  Firefox seems to be more finicky about `resolve()` needing to be called.  This seems to be the core of the issue.  More to come as I investigate production examples.

**Comment by mekline** [comment]
I believe this can be closed per the recent PR, @okaycj please revert if not!
