### ISSUE TITLE
Fix video freeze issue for everd_no-databrary branch

### ISSUE THREAD

**Issue by mekline** [lookit/ember-lookit-frameplayer#298]
**Describe the bug**
Branch for Erica Verde still showing video freeze difficulties; could be resulting from either SHA reverted to main/master branch *or* everd_nodatabrary SHA not including new fixes. 

**To Reproduce**
(Erica can provide an example in the comments below)

**Additional information**

This is the custom branch at issue: https://github.com/lookit/ember-lookit-frameplayer/tree/everde_no-databrary

**Comment by everde** [comment]
Hi all, of course, now it's back to working just fine!

**Comment by mekline** [comment]
Closing-resolved!
