### ISSUE TITLE
Add child and response data to exit URL querystring

### ISSUE THREAD

**Issue by okaycj** [lookit/ember-lookit-frameplayer#302]
# Summary
With external studies we currently add the child's hashed anonymized ID and the response's UUID to the query string of the study URL.  The same needs be done with the exit URL for EFP studies.  

An example of the external study URL augmentation can be see [here](https://github.com/lookit/lookit-api/blob/develop/web/views.py#L596) and [here](https://github.com/lookit/lookit-api/blob/develop/web/views.py#L45).  The code the _probably_ needs to be updated on the EFP side is [here](https://github.com/lookit/ember-lookit-frameplayer/blob/develop/app/components/exp-player/component.js#L195).

# Acceptance Criteria

- [ ] Get the child's hashed ID and response ID from the API.
- [ ] Add add ID's to URL without altering any existing query string parameters. 
- [ ] Tests to prove the change works.

**Comment by mekline** [comment]
@okaycj can this issue be closed?
