### ISSUE TITLE
Add more frames to cover common tasks

### ISSUE THREAD

**Issue by kimberscott** [lookit/ember-lookit-frameplayer#72]
Build out the library of experimental components to include more easy-to-use frames for common tasks:

* [x] Remove extraneous docs (e.g. deprecated physics-only frames) to reduce confusion
* [x] Frame to display the user's webcam, intended for a break / position check. Customize text.
* [x] Add video examples of existing frames
* [x] Frame to do alternation/change-detection task. 
  - image lists A and B for left and right. 
  - whether to start A or B
  - whether to order all randomly within lists.  
  - total duration
  - wait for pre-load of all images
  - duration on and off in ms
  - whether to show border
  - whether to do attn-grabber at all
  - store appropriate data but reduce overall event data stored
  - fix fetch behavior in expandAssets to notify upon any missing files
  - add docs ideally w video
* [x] exp-lookit-preview, exp-lookit-preview-explanation: combine so that there isn't the odd need to put them right next to each other for them to work properly. Make the preview-explanation optional. (absorbing #108 )
* [x] Set up video-config frame to require checking for persistent permissions (see screenshots/notes from @jchu10 )
* [x] Improvements to consent form:
  - https://github.com/lookit/ember-lookit-frameplayer/issues/141
  - Template #3 with Risks, benefits, & payment section per UBC
  - Option to ask additional adults to also consent for UW Madison
* Frames to show image and/or audio. Create general underlying frame plus extensions with simplified options for expected use cases: 
    * [x] Create general frame as starting point
    * [x] Variant 1: Show one image. Choose next button or auto-advance after time. Region for parent-text. Specify position to fill image area OR provide height/width and top/left values. Optional whether should have region for parent-text (may be same frame)
    * [x] Variant 2: Frame to show image + audio. As above; choose next button or auto-advance after audio. Optional replay.
    * [x] Variant 3: Frame to show N images with defaults for center, left, right placement. Optional audio. Auto-advance after time.
    * [x] Variant 4: Frame to show N options (images) and require clicking on one. Optional confirm or immediately proceed. Optional audio.
    * [x] Variant 5: As above, but limit set of choices. Allow specifying timing of appearance of any image. (Intended for standard reaction time experiments)
    * [x] Variant 6: "Training" version of below per comment
    * [x] Add back in the "highlighting" timing from exp-lookit-story-page since it seems like it might be more generally useful. Documentation with videos for all frames.
* [x] Frame to do just calibration and/or attention-grabber (wait for session recording to start if needed)
* [x] Frame to show a video and optional audio. Choose proceed automatically or next button. Allow specification of video size (incl. fill). Choose proceed automatically after video, proceed automatically after audio, proceed automatically after N seconds, or next button. Choose loop audio, loop video. 
* [x] Frames for easy starting/stopping session recording, as alternative to including parameters on functional frames.

**Feedback about what would be most helpful to you for your study designs is very welcome!** Comment below.

You can also **try out frames in progress** by updating your experiment runner to the most recent commit of [this branch](https://github.com/lookit/ember-lookit-frameplayer/commits/72-frame-additions-and-revisions). Changes aren't reflected in the frame docs yet, though, so you'd have to dig a little in the code to see parameters to use.

**Comment by qianmiao90** [comment]
For your component "**Frame to show N options (images) and require clicking on one. Optional confirm or immediately proceed. Optional audio**."  Would it be possible to set such condition, so that 
if clicking on the correct image, it proceeds;
else if clicking on the incorrect one, an error message appears and it proceeds only after clicking the correct image.

**Comment by kimberscott** [comment]
Yes, the sequence of selections & timing will be recorded regardless.

The more general version I might propose is the following: along with each image, you specify (a) whether clicking it should advance to the next frame,  (b) an optional audio file to play upon clicking it (during which time nothing else can be clicked on), (c) optional text to display upon clicking it (have to think about where and for how long it's displayed). But happy to consider special-case versions or extensions depending on other expected uses - if you'd also use this frame or want to do something similar, please chime in here!

**Comment by kimberscott** [comment]
May add start/end session recording "placeholder" frames to make writing sequence more straightforward, although this can also still be done within individual frames
